apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: snyky-pipeline
spec:
  resources:
    - name: source-repo
      type: git
  tasks:
    - name: conftest-verify
      taskRef:
        name: conftest-verify
      resources:
        inputs:
          - name: source
            resource: source-repo
    - name: pipfile-conftest
      taskRef:
        name: conftest
      runAfter:
        - conftest-verify
      params:
        - name: files
          value: Pipfile
        - name: args
          value:
            - --input
            - toml
            - --namespace
            - pipfile
      resources:
        inputs:
          - name: source
            resource: source-repo
    - name: dockerfile-conftest
      taskRef:
        name: conftest
      runAfter:
        - conftest-verify
      params:
        - name: files
          value: Dockerfile
        - name: args
          value:
            - --namespace
            - docker
      resources:
        inputs:
          - name: source
            resource: source-repo
    - name: pytest-conftest
      taskRef:
        name: conftest
      runAfter:
        - conftest-verify
      params:
        - name: files
          value: pytest.ini
        - name: args
          value:
            - --namespace
            - pytest
      resources:
        inputs:
          - name: source
            resource: source-repo
    - name: helm-conftest
      taskRef:
        name: helm-conftest
      runAfter:
        - conftest-verify
      params:
        - name: chart
          value: snyky
      resources:
        inputs:
          - name: source
            resource: source-repo
    - name: snyk
      taskRef:
        name: snyk-python
      resources:
        inputs:
          - name: source
            resource: source-repo
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: snyky-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/garethr/snyky.git
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: conftest-verify
spec:
  inputs:
    resources:
    - name: source
      type: git
      targetPath: source
  steps:
  - name: conftest-verify
    workingdir: /workspace/source
    image: instrumenta/conftest:latest
    command:
      - conftest
      - verify

