version: 2.1
orbs:
  conftest: kenfdev/conftest-orb@0.0.9
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
        environment:
            PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "Pipfile.lock" }}
            - deps-
      - run:
          name: install dependencies
          command: |
            pipenv install --dev
      - save_cache:
          paths:
            - .venv
          key: deps-{{ checksum "Pipfile.lock" }}
      - conftest/install
      - run:
          name: run tests
          command: |
            pipenv run pytest
