on: push
name: Policy
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test pytest.ini
      uses: instrumenta/conftest-action@master
      with:
        files: pytest.ini
        namespace: pytest
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test Dockerfile
      uses: instrumenta/conftest-action@master
      with:
        files: Dockerfile
        namespace: docker
  helm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test Helm Chart
      uses: instrumenta/conftest-action/helm@master
      with:
        chart: snyky
