on: push
name: Policy
jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test pytest.ini
      uses: instrumenta/conftest-action@master
      with:
        files: pytest.ini
        namespace: pytest
