on: push
name: Testing
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: security
      uses: actions/docker/cli@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: build --build-arg SNYK_TOKEN --target Security .

  image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: actions/docker/cli@master
      env:
          DOCKER_BUILDKIT: 1
      with:
        args: build -t sample .
    - name: snyk-image
      uses: docker://garethr/snyk-cli:docker
      env:
        PROJECT_PATH: /github/workspace
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        entrypoint: sh
        args: -c /docker-entrypoint.sh test --docker sample --file=Dockerfile
